-- ALL SQL statement under below is used step by step in Snowflake worksheet

-- USE ROLE FIVETRAN_ROLE;
-- USE DATABASE FIVETRAN_DATABASE;
-- CREATE SCHEMA IF NOT EXISTS MLDS430_KOALA_INDEX_RAW
-- GRANT USAGE ON SCHEMA FIVETRAN_DATABASE.MLDSFIVETRAN_DATABASE.MLDS430_KOALA_INDEX_RAW430_KOALA_INDEX_RAW TO ROLE FIVETRAN_ROLE
-- USE SCHEMA MLDS430_KOALA_INDEX_RAW;
-- CREATE OR REPLACE TABLE INDEX_DAILY_2019_2023_FILTERED AS SELECT * FROM FIVETRAN_DATABASE.S3.INDEX_DAILY_2019_2023_FILTERED;FIVETRAN_DATABASE.MLDS430_KOALA_INDEX_RAW
-- select * FROM INDEX_DAILY_2019_2023_FILTERED WHERE TABLE_NAME = 1000001 ORDER BY DATE LIMIT 10
-- SELECT * FROM STG_INDEX_DAILY limit 10;