mlds_430_snowflake:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "azb79167"
      user: "KOALA"
      role: "FIVETRAN_ROLE"
      database: "FIVETRAN_DATABASE"
      warehouse: "FIVETRAN_WAREHOUSE"
      schema: "MLDS430_KOALA_INDEX_RAW"
      threads: 4
      client_session_keep_alive: false

      private_key_path: /usr/local/airflow/dbt/index_dbt/keys/rsa_key.p8
      private_key_passphrase: "MLDS430HW2"
